apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox-echo
  name: busybox-echo
  namespace: practice 
spec:
  containers:
  - image: busybox
    name: busybox-echo
    command: ['sh','-c','echo "Hello world"']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
