apiVersion: v1
kind: Pod
metadata:
  name: web
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:1.11.9-alpine
      ports:
        - name: web
          containerPort: 80
          containerPort: 443
